let list = [
    { artist: 'Deep Purple', song: 'Child in Time', score: 98, id: 1 },
    { artist: 'Led Zeppelin', song: 'Good Times, Bad Times', score: 97, id: 2 },
    { artist: 'The Beatles', song: 'Yesterday', score: 96, id: 3 },
    { artist: 'Jimi Hendrix', song: 'Little Wing', score: 95, id: 3 },
    { artist: 'Paul McCartney', song: "Maybe I'm Amazed", score: 99, id: 5 },
    { artist: 'Eric Johnson', song: 'Cliffs of Dover', score: 94, id: 6 },
    { artist: 'Pink Floyd', song: "Wish You Were Here", score: 93, id: 7 },
    { artist: 'The Who', song: "My Generation", score: 86, id: 8 },
    { artist: 'Aerosmith', song: "Dream On", score: 86, id: 9 },
    { artist: 'Derek and the Dominos', song: "Layla", score: 84, id: 10 },
    { artist: 'Cream', song: "Sunshine of Your Love", score: 84, id: 11 },
    { artist: 'Dire Straits', song: "Sultans of Swing", score: 87, id: 12 },
    { artist: 'Queen', song: "We Will Rock You", score: 88, id: 13 },
    { artist: 'Eagles', song: "Hotel California", score: 87, id: 14 },
    { artist: 'Lynyrd Skynyrd', song: "Simple Man", score: 82, id: 15 },
    { artist: 'The Allman Brothers Band', song: "Jessica", score: 85, id: 16 },
    { artist: 'Fleetwood Mac', song: "The Chain", score: 77, id: 17 },
    { artist: 'AC/DC', song: "Back in Black", score: 70, id: 18 },
    { artist: 'David Bowie', song: "Space Oddity", score: 83, id: 19 },
    { artist: 'Elvis Presley', song: "Suspicious Minds", score: 72, id: 20 },
    { artist: 'Neil Young', song: "Old Man", score: 82, id: 21 },
    { artist: 'Oasis', song: "Don't Look Back in Anger", score: 89, id: 22 },
    { artist: 'Red Hot Chilli Peppers', song: "Under the Bridge", score: 89, id: 23 },
    { artist: 'Foo Fighters', song: "Everlong", score: 91, id: 24 },
    { artist: 'Pearl Jam', song: "Alive", score: 92, id: 25 },
    { artist: 'The Smiths', song: "How Soon is Now", score: 80, id: 26 },
    { artist: 'Radiohead', song: "Paranoid Android", score: 90, id: 27 },
    { artist: 'Jet', song: "Are You Gonna Be My Girl", score: 76, id: 28 },
    { artist: 'Arctic Monkeys', song: "Do I Wanna Know?", score: 76, id: 29 },
    { artist: 'Audioslave', song: "Like a Stone", score: 76, id: 30 },
    { artist: 'Panic! At The Disco', song: "The Ballad of Mona Lisa", score: 81, id: 31 },
    { artist: 'Jeff Buckley', song: "Forget Her", score: 78, id: 32 },
    { artist: 'Alanis Morissette', song: "You Oughta Know", score: 74, id: 33 },
    { artist: 'John Mayer', song: "Slow Dancing in a Burning Room", score: 79, id: 34 },
    { artist: 'Gorillaz', song: "Every Melancholy We Reach is Hill", score: 80, id: 35 },
    { artist: 'System of a Down', song: "Hypnotize", score: 77, id: 36 },
    { artist: 'Blondie', song: "Maria", score: 73, id: 37 },
    { artist: 'White Stripes', song: "Seven Nation Army", score: 75, id: 38 },
    { artist: 'Bad Company', song: "Bad Company", score: 75, id: 39 },
    { artist: 'Kansas', song: "Carry On Wayward Son", score: 82, id: 40 },
    { artist: 'Simon & Garfunkel', song: "I Am a Rock", score: 71, id: 41 },
    { artist: 'Scorpions', song: "No One Like You", score: 70, id: 42 },
    { artist: 'Hozier', song: "Almost (Sweet Music)", score: 65, id: 43 },
    { artist: 'Tom Petty', song: "Wildflowers", score: 67, id: 44 },
    { artist: 'Dolly Parton', song: "Jolene", score: 68, id: 45 },
    { artist: 'The Stranglers', song: "Golden Brown", score: 69, id: 46 },
    { artist: 'Gary Moore', song: "Still Got the Blues (For You)", score: 75, id: 47 },
    { artist: 'No Doubt', song: "Don't Speak", score: 73, id: 48 },
    { artist: 'The Clash', song: "Should I Stay or Should I Go", score: 72, id: 49 },
    { artist: 'Steve Vai', song: "Tender Surrender", score: 75, id: 50 }
];